export type Theme = {
  primaryColor?: string
  secondaryColor?: string
  fontFamily?: string
  boxShadow?: string
  primaryTextColor?: string
  secondaryTextColor?: string
  borderWidth?: string
  borderStyle?: string
  borderColor?: string
  borderRadius?: string
  breakpoints?: {
    small?: string
    medium?: string
    large?: string
    extraLarge?: string
  }
  fontSize?: {
    small?: string
    medium?: string
    large?: string
  }
  comboBox?: {
    height?: string
    margin?: string
    padding?: string
    borderColor?: string
    borderWidth?: string
    borderStyle?: string
    borderRadius?: string
    color?: string
    bgColor?: string
    focusedBorderColor?: string
    focusedColor?: string
    focusedBgColor?: string
    errorBorderColor?: string
    errorColor?: string
    errorBgColor?: string
    disabledColor?: string
    disabledBorderColor?: string
    disabledBgColor?: string
    hoverColor?: string
    hoverBorderColor?: string
    hoverBgBorder?: string
    button: {
      height?: string
      width?: string
      bgColor?: string
      color?: string
    }
    item: {
      margin?: string
      height?: string
      padding?: string
      borderWidth?: string
      borderStyle?: string
      borderColor?: string
      borderRadius?: string
      bgColor?: string
      color?: string
      hoverBgColor?: string
      hoverColor?: string
      disabledBgColor?: string
      disabledColor?: string
      selectedBgColor?: string
      selectedColor?: string
    }
  }
  input?: {
    height?: string
    margin?: string
    padding?: string
    borderColor?: string
    borderWidth?: string
    borderStyle?: string
    borderRadius?: string
    color?: string
    bgColor?: string
    focusedBorderColor?: string
    focusedColor?: string
    focusedBgColor?: string
    errorBorderColor?: string
    errorColor?: string
    errorBgColor?: string
    disabledColor?: string
    disabledBorderColor?: string
    disabledBgColor?: string
    hoverColor?: string
    hoverBorderColor?: string
    hoverBgBorder?: string
  }
  textArea?: {
    height?: string
    margin?: string
    padding?: string
    borderColor?: string
    borderWidth?: string
    borderStyle?: string
    borderRadius?: string
    color?: string
    bgColor?: string
    focusedBorderColor?: string
    focusedColor?: string
    focusedBgColor?: string
    errorBorderColor?: string
    errorColor?: string
    errorBgColor?: string
    disabledColor?: string
    disabledBorderColor?: string
    disabledBgColor?: string
    hoverColor?: string
    hoverBorderColor?: string
    hoverBgBorder?: string
  }
  button?: {
    fontWeight?: string
    margin?: string
    padding?: string
    borderColor?: string
    borderWidth?: string
    borderStyle?: string
    borderRadius?: string
    bgColor?: string
    color?: string
    hoverBgColor?: string
    hoverColor?: string
    hoverBorderColor?: string
    activeBgColor?: string
    activeColor?: string
    activeBorderColor?: string
    disabledBgColor?: string
    disabledColor?: string
    disabledBorderColor?: string
    primary?: {
      borderColor?: string
      borderRadius?: string
      bgColor?: string
      color?: string
      hoverBgColor?: string
      hoverColor?: string
      hoverBorderColor?: string
      activeBgColor?: string
      activeColor?: string
      activeBorderColor?: string
      disabledBgColor?: string
      disabledColor?: string
      disabledBorderColor?: string
    }
  }
}
