import { Theme } from "../types"
import { createTheme } from "../utils/createTheme"

const themeValues: Theme = {
  primaryColor: "#99bbe8",
  bodyBgColor: "#fff",
  componentBgColor: "#fff",
  fontFamily: "arial, tahoma, verdana, helvetica, -apple-system",
  textColor: "rgb(0, 0, 0)",
  textColorSecondary: "rgba(0, 0, 0, 0.75)",
  breakpoints: {
    // xs: "max-width: 575.98px",
    sm: "max-width: 767.98px",
    md: "max-width: 991.98px",
    lg: "max-width: 1199.98px",
  },
  fontSize: {
    sm: "11px",
    md: "12px",
    lg: "14px",
  },
  borderWidth: "1px",
  borderStyle: "solid",
  borderColor: "#ccc",
  borderRadius: "0",
  button: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "rgb(153, 187, 232)",
    borderRadius: "5px",
    margin: "0",
    fontWeight: "700",
    padding: "12px 24px",
    // bgColor: "#fff",
    // color: "black",
    hoverBgColor: "rgb(217, 235, 251)",
    // hoverColor: "black",
    hoverBorderColor: "rgb(153, 187, 232)",
    activeBgColor: "#b6cbe4",
    // activeColor: "black",
    activeBorderColor: "1px solid #b6cbe4",
    primary: {
      borderColor: "rgb(153, 187, 232)",
      borderRadius: "5px",
      // bgColor: "rgb(217, 235, 251)",
      // color: "black",
      hoverBgColor: "rgba(221, 239, 255, 0.55)",
      // hoverColor: "black",
      hoverBorderColor: "rgb(153, 187, 232)",
      activeBgColor: "#b6cbe4",
      // activeColor: "black",
      activeBorderColor: "#b6cbe4",
    },
  },
  label: {
    margin: "0",
    // color: "#000",
    padding: "0 5px 0 0",
  },
  input: {
    height: "24px",
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    margin: "0",
    padding: "0",
    // bgColor: "#fff",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // focusedColor: "black",
    // focusedBgColor: "#fff",
    errorBorderColor: "red",
    // errorColor: "black",
    // errorBgColor: "#fff",
    disabledColor: "rgba(0, 0, 0, 0.75)",
    // disabledBorderColor: "#ccc",
    disabledBgColor: "rgba(239, 239, 239, 0.5)",
    // hoverColor: "black",
    // hoverBorderColor: "#99bbe8",
    // hoverBgColor: "#fff",
  },
  textArea: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // margin: "0",
    // padding: "0",
    // bgColor: "#fff",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // focusedColor: "black",
    // focusedBgColor: "#fff",
    // errorBorderColor: "red",
    // errorColor: "black",
    // errorBgColor: "#fff",
    // disabledColor: "rgba(0, 0, 0, 0.75)",
    // disabledBorderColor: "#ccc",
    // disabledBgColor: "rgba(239, 239, 239, 0.5)",
    // hoverColor: "black",
    // hoverBorderColor: "#99bbe8",
    // hoverBgColor: "#fff",
  },
  comboBox: {
    height: "24px",
    // margin: "0",
    // padding: "0",
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // bgColor: "#fff",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // focusedColor: "black",
    // focusedBgColor: "#fff",
    // errorBorderColor: "red",
    // errorColor: "black",
    // errorBgColor: "#fff",
    // disabledColor: "rgba(0, 0, 0, 0.75)",
    // disabledBorderColor: "#ccc",
    // disabledBgColor: "rgba(239, 239, 239, 0.5)",
    // hoverColor: "black",
    // hoverBorderColor: "#99bbe8",
    // hoverBgColor: "#fff",
    button: {
      height: "22px",
      width: "22px",
      bgColor: "#f2f0f0",
      color: "#999",
    },
    item: {
      margin: "0",
      height: "18px",
      padding: "2px 6px",
      borderWidth: "0",
      // borderStyle: "solid",
      // borderColor: "#ccc",
      // borderRadius: "0",
      // bgColor: "#fff",
      // color: "#000",
      hoverBgColor: "#eee",
      // hoverColor: "#000",
      // disabledBgColor: "#fff",
      disabledColor: "rgba(0, 0, 0, 0.33)",
      selectedBgColor: "#ccddf3",
      // selectedColor: "#000",
    },
  },
  calendar: {
    margin: "0",
    height: "18px",
    padding: "2px 6px",
    // color: #000,
    // borderColor: "#aeaeae",
    borderRadius: "0.3rem",
    // bgColor: "#fff",
    hoverBgColor: "#eee",
    // hoverColor: "#000",
    keyboardHoverBgColor: "#2a87d0",
    // keyboardHoverColor: "#fff",
    selectedBgColor: "#216ba5",
    selectedColor: "#fff",
    // todayBgColor: "#99bbe8",
    // todayColor: "#000",
    header: {
      bgColor: "#f0f0f0",
      // borderWidth: "1px",
      // borderStyle: "solid",
      // borderColor: "#aeaeae",
    },
    closeIcon: {
      bgColor: "#216ba5",
      color: "#fff",
    },
  },
  tree: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // focusedBorderColor: "#99bbe8",
    errorBorderColor: "red",
    // hoverBorderColor: "#99bbe8",
    node: {
      margin: "0",
      padding: "5px 8px",
      // borderWidth: "0",
      // borderStyle: "solid",
      // borderColor: "#ccc",
      // borderRadius: "0",
      bgColor: "transparent",
      // color: "#000",
      hoverBgColor: "#eee",
      label: {
        bgColor: "transparent",
        selectedBgColor: "#dae6f4",
      },
    },
  },
  checkboxGroup: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // errorBorderColor: "red",
    // hoverBorderColor: "#99bbe8",
  },
  radioGroup: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // errorBorderColor: "red",
    // hoverBorderColor: "#99bbe8",
  },
  duallist: {
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    // borderRadius: "0",
    // color: "black",
    // focusedBorderColor: "#99bbe8",
    // errorBorderColor: "red",
    // hoverBorderColor: "#99bbe8",
  },
  toolbar: {
    bgColor: "linear-gradient(#dae6f4, #d0def0)",
    // borderWidth: "1px",
    // borderStyle: "solid",
    // borderColor: "#99bbe8",
    // borderRadius: "0",
    button: {
      bgColor: "transparent",
      // borderWidth: "1px",
      // borderStyle: "solid",
      // borderColor: "transparent",
      // borderRadius: "0",
      hoverBgColor: "#ddefff",
      hoverBorderWidth: "1px",
      hoverBorderStyle: "solid",
      // hoverBorderColor: "#99bbe8",
    },
  },
  tabPanel: {
    color: "rgb(21, 66, 139)",
    tab: {
      bgColor: "linear-gradient(#dae6f4, #d0def0)",
      selectedBgColor: "#d7e4f3",
      // borderWidth: "1px",
      // borderStyle: "solid",
      borderColor: "#99bbe8",
      // borderRadius: "0",
    },
  },
  form: {
    padding: "5px 0 0 10px",
    errorColor: "red",
    field: {
      margin: "0 0 1em 0",
      control: {
        maxWidth: "150px",
      },
    },
    label: {
      maxWidth: "200px",
      minWidth: "150px",
    },
    fieldSet: {
      // borderWidth: "1px",
      // borderStyle: "solid",
      // borderColor: "rgb(81, 162, 238)",
      borderRadius: "5px",
    },
    legend: {
      // color: "rgb(81, 162, 238)",
      margin: "0 5px",
    },
  },
  link: {
    color: "rgb(21, 66, 139)",
    textDecoration: "underline",
  },
  breadcrumbs: {
    color: "currentColor",
  },
  grid: {
    color: "black",
    header: {
      color: "black",
      bgColor: "#ededed",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "#ddd",
      borderRadius: "0",
    },
    row: {
      color: "black",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "#ededed",
      borderRadius: "0",
      bgColor: "transparent",
      oddBgColor: "#fafafa",
      hoverBgColor: "#eee",
      selectedBgColor: "#dfe8f6",
      selectedBorderColor: "#b7cefd",
    },
    pagingBar: {
      color: "black",
      borderWidth: "1px",
      borderStyle: "solid",
      borderColor: "rgb(153, 187, 232)",
      borderRadius: "0",
      bgColor: "linear-gradient(rgb(218, 230, 244), rgb(208, 222, 240))",
    },
  },
  modal: {
    // borderWidth: "0",
    // borderStyle: "solid",
    // borderColor: "#ccc",
    borderRadius: "5px",
    // bgColor: "#fff",
    closeButtonColor: "rgb(21, 66, 139)",
    header: {
      // borderWidth: "0",
      // borderStyle: "",
      // borderColor: "",
      borderRadius: "5px",
      bgColor: "linear-gradient(rgb(255, 255, 255), rgb(208, 222, 240))",
      color: "rgb(21, 66, 139)",
    },
  },
}

const theme = createTheme(themeValues)

export { theme as jepriaTheme }
